// frontend/src/pages/SigninPage.tsx
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { LogIn, PlayCircle, UserPlus } from "lucide-react";
import { supabase } from "../lib/supabase";
import { useAuth } from "../contexts/AuthContext";
import { InteractiveElement } from "../components/InteractiveElement";

export default function SigninPage() {
  const navigate = useNavigate();
  const { session } = useAuth();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isSignUp, setIsSignUp] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // Redirect if already authenticated
  useEffect(() => {
    if (session) {
      navigate("/dashboard");
    }
  }, [session, navigate]);

  // Background interactive bubble
  useEffect(() => {
    const interBubble = document.querySelector(
      ".signin-interactive"
    ) as HTMLElement;

    if (interBubble) {
      let curX = 0;
      let curY = 0;
      let tgX = 0;
      let tgY = 0;

      function moveBg() {
        curX += (tgX - curX) / 20;
        curY += (tgY - curY) / 20;
        interBubble.style.transform = `translate(${Math.round(
          curX
        )}px, ${Math.round(curY)}px)`;
        requestAnimationFrame(moveBg);
      }

      const handleBgMouseMove = (event: MouseEvent) => {
        tgX = event.clientX;
        tgY = event.clientY;
      };

      window.addEventListener("mousemove", handleBgMouseMove);
      moveBg();

      return () => {
        window.removeEventListener("mousemove", handleBgMouseMove);
      };
    }
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      if (isSignUp) {
        // Simple sign up
        const { error } = await supabase.auth.signUp({
          email,
          password,
        });

        if (error) throw error;

        alert(
          "Registration successful! Please check your email for verification."
        );
        setIsSignUp(false);
      } else {
        // Sign in
        const { error } = await supabase.auth.signInWithPassword({
          email,
          password,
        });

        if (error) throw error;
      }
    } catch (error: any) {
      setError(error.message || "An error occurred");
    } finally {
      setLoading(false);
    }
  };

  const handleDemoLogin = async () => {
    setLoading(true);
    setError("");

    try {
      // Try to sign in with demo credentials
      const { error } = await supabase.auth.signInWithPassword({
        email: "demo@gmail.com",
        password: "verifiedcc",
      });

      if (error) {
        // If demo user doesn't exist, show helpful message
        if (error.message.includes("Invalid login credentials")) {
          setError(
            "Demo user not found. Please create a demo user in your Supabase dashboard with email: demo@gmail.com and password: verifiedcc"
          );
        } else {
          throw error;
        }
      }

      // AuthContext will automatically redirect to dashboard
    } catch (error: any) {
      setError(error.message || "Demo login failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <div className="gradient-bg">
        <svg xmlns="http://www.w3.org/2000/svg">
          <defs>
            <filter id="goo">
              <feGaussianBlur
                in="SourceGraphic"
                stdDeviation="10"
                result="blur"
              />
              <feColorMatrix
                in="blur"
                mode="matrix"
                values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -8"
                result="goo"
              />
              <feBlend in="SourceGraphic" in2="goo" />
            </filter>
          </defs>
        </svg>
        <div className="gradients-container">
          <div className="g1"></div>
          <div className="g2"></div>
          <div className="g3"></div>
          <div className="g4"></div>
          <div className="g5"></div>
          <div className="interactive signin-interactive"></div>
        </div>
      </div>
      <main className="min-h-screen relative z-10 flex items-center justify-center p-6">
        <div className="max-w-md mx-auto">
          <div className="bg-white/80 backdrop-blur-lg rounded-2xl p-8 border border-gray-200/50 shadow-2xl">
            <div className="text-center mb-6">
              <img
                src="/verifiedcc-logo.png"
                alt="VerifiedCC Logo"
                className="h-16 w-auto mx-auto mb-4"
              />
              <h3 className="text-2xl font-bold text-deep-ocean">
                {isSignUp ? "Become Our Partner" : "Become Our Partner"}
              </h3>
              <p className="text-gray-600 mt-2">
                {isSignUp
                  ? "Partner Registration"
                  : "Access Guardian Verifiable Credentials Portal"}
              </p>
              {error && (
                <div className="mt-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg text-sm">
                  {error}
                </div>
              )}
            </div>

            {!isSignUp ? (
              <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                  <label
                    htmlFor="email"
                    className="block text-sm font-medium text-deep-ocean mb-2"
                  >
                    Email Address
                  </label>
                  <input
                    type="email"
                    id="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oasis-green focus:border-transparent transition-colors bg-white/50"
                    placeholder="partner@company.com"
                  />
                </div>

                <div>
                  <label
                    htmlFor="password"
                    className="block text-sm font-medium text-deep-ocean mb-2"
                  >
                    Password
                  </label>
                  <input
                    type="password"
                    id="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oasis-green focus:border-transparent transition-colors bg-white/50"
                    placeholder="••••••••"
                  />
                  <p className="text-xs text-gray-500 mt-1">
                    Demo credentials:{" "}
                    <code className="bg-gray-100 px-1 rounded">
                      demo@gmail.com
                    </code>{" "}
                    /{" "}
                    <code className="bg-gray-100 px-1 rounded">verifiedcc</code>
                  </p>
                </div>

                {email && password ? (
                  <InteractiveElement
                    as="button"
                    size="small"
                    backgroundStyle="full" // This gives it the full signin page background
                    type="submit"
                    disabled={loading}
                    className="w-full text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
                  >
                    {loading ? (
                      <div className="flex items-center justify-center">
                        <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                        Signing In...
                      </div>
                    ) : (
                      <>
                        <LogIn className="w-5 h-5 inline mr-2" />
                        Access Dashboard
                      </>
                    )}
                  </InteractiveElement>
                ) : (
                  <button
                    type="submit"
                    disabled={loading}
                    className="w-full text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none bg-gray-400"
                  >
                    {loading ? (
                      <div className="flex items-center justify-center">
                        <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                        Signing In...
                      </div>
                    ) : (
                      <>
                        <LogIn className="w-5 h-5 inline mr-2" />
                        Access Dashboard
                      </>
                    )}
                  </button>
                )}
              </form>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-6">
                <div>
                  <label
                    htmlFor="signup_email"
                    className="block text-sm font-medium text-deep-ocean mb-2"
                  >
                    Email Address
                  </label>
                  <input
                    type="email"
                    id="signup_email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oasis-green focus:border-transparent transition-colors bg-white/50"
                    placeholder="partner@company.com"
                  />
                </div>

                <div>
                  <label
                    htmlFor="signup_password"
                    className="block text-sm font-medium text-deep-ocean mb-2"
                  >
                    Password
                  </label>
                  <input
                    type="password"
                    id="signup_password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                    className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oasis-green focus:border-transparent transition-colors bg-white/50"
                    placeholder="••••••••"
                  />
                </div>

                <div className="flex gap-3">
                  <button
                    type="submit"
                    disabled={loading}
                    className="flex-1 bg-oasis-green hover:bg-green-700 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
                  >
                    {loading ? (
                      <div className="flex items-center justify-center">
                        <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                        Creating Account...
                      </div>
                    ) : (
                      <>
                        <UserPlus className="w-5 h-5 inline mr-2" />
                        Create Account
                      </>
                    )}
                  </button>
                  <button
                    type="button"
                    onClick={() => setIsSignUp(false)}
                    className="flex-1 bg-gray-500 hover:bg-gray-600 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300"
                  >
                    Cancel
                  </button>
                </div>
              </form>
            )}

            {!isSignUp && (
              <div className="mt-4">
                <div className="relative">
                  <div className="absolute inset-0 flex items-center">
                    <div className="w-full border-t border-gray-300"></div>
                  </div>
                  <div className="relative flex justify-center text-sm">
                    <span className="px-2 bg-white/80 text-gray-500">Or</span>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleDemoLogin}
                  disabled={loading}
                  className="w-full mt-4 bg-gray-500 hover:bg-gray-600 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
                >
                  {loading ? (
                    <div className="flex items-center justify-center">
                      <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                      Loading Demo...
                    </div>
                  ) : (
                    <>
                      <PlayCircle className="w-5 h-5 inline mr-2" />
                      Try Demo Account
                    </>
                  )}
                </button>
              </div>
            )}

            <div className="mt-6 text-center">
              <p className="text-sm text-gray-600">
                {isSignUp ? "Already have an account?" : "New partner?"}{" "}
                <button
                  type="button"
                  onClick={() => setIsSignUp(!isSignUp)}
                  className="text-oasis-green hover:text-green-700 font-medium underline"
                >
                  {isSignUp ? "Sign in here" : "Sign up for partnership"}
                </button>
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

// frontend-solid/src/pages/SigninPage.tsx
import { Component, createSignal, onMount, onCleanup, createEffect } from "solid-js";
import { useNavigate } from "@solidjs/router";
import { LogIn, PlayCircle, UserPlus } from "lucide-solid";
import { supabase } from "../lib/supabase";
import { useAuth } from "../contexts/AuthContext";
import { InteractiveElement } from "../components/InteractiveElement";
import { BouncyDotsLoader } from "../components/BouncyDotsLoader";

const SigninPage: Component = () => {
  const navigate = useNavigate();
  const { session } = useAuth();
  const [email, setEmail] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [isSignUp, setIsSignUp] = createSignal(false);
  const [loading, setLoading] = createSignal(false);
  const [error, setError] = createSignal("");

  // Redirect if already authenticated
  createEffect(() => {
    if (session()) {
      navigate("/dashboard");
    }
  });

  // Background interactive bubble
  onMount(() => {
    const interBubble = document.querySelector(
      ".signin-interactive"
    ) as HTMLElement;

    if (interBubble) {
      let curX = 0;
      let curY = 0;
      let tgX = 0;
      let tgY = 0;
      let animationId: number;

      function moveBg() {
        curX += (tgX - curX) / 20;
        curY += (tgY - curY) / 20;
        interBubble.style.transform = `translate(${Math.round(
          curX
        )}px, ${Math.round(curY)}px)`;
        animationId = requestAnimationFrame(moveBg);
      }

      const handleBgMouseMove = (event: MouseEvent) => {
        tgX = event.clientX;
        tgY = event.clientY;
      };

      window.addEventListener("mousemove", handleBgMouseMove);
      moveBg();

      onCleanup(() => {
        window.removeEventListener("mousemove", handleBgMouseMove);
        if (animationId) {
          cancelAnimationFrame(animationId);
        }
      });
    }
  });

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    try {
      if (isSignUp()) {
        // Simple sign up
        const { error } = await supabase.auth.signUp({
          email: email(),
          password: password(),
        });

        if (error) throw error;

        alert(
          "Registration successful! Please check your email for verification."
        );
        setIsSignUp(false);
      } else {
        // Sign in
        const { error } = await supabase.auth.signInWithPassword({
          email: email(),
          password: password(),
        });

        if (error) throw error;
      }
    } catch (error: any) {
      setError(error.message || "An error occurred");
    } finally {
      setLoading(false);
    }
  };

  const handleDemoLogin = async () => {
    setLoading(true);
    setError("");

    try {
      // Try to sign in with demo credentials
      const { error } = await supabase.auth.signInWithPassword({
        email: "demo@gmail.com",
        password: "verifiedcc",
      });

      if (error) {
        // If demo user doesn't exist, show helpful message
        if (error.message.includes("Invalid login credentials")) {
          setError(
            "Demo user not found. Please create a demo user in your Supabase dashboard with email: demo@gmail.com and password: verifiedcc"
          );
        } else {
          throw error;
        }
      }

      // AuthContext will automatically redirect to dashboard
    } catch (error: any) {
      setError(error.message || "Demo login failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <div class="gradient-bg">
        <svg xmlns="http://www.w3.org/2000/svg">
          <defs>
            <filter id="goo">
              <feGaussianBlur
                in="SourceGraphic"
                stdDeviation="10"
                result="blur"
              />
              <feColorMatrix
                in="blur"
                type="matrix"
                values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -8"
                result="goo"
              />
              <feBlend in="SourceGraphic" in2="goo" />
            </filter>
          </defs>
        </svg>
        <div class="gradients-container">
          <div class="g1"></div>
          <div class="g2"></div>
          <div class="g3"></div>
          <div class="g4"></div>
          <div class="g5"></div>
          <div class="interactive signin-interactive"></div>
        </div>
      </div>
      <main class="min-h-screen relative z-10 flex items-center justify-center p-6">
        <div class="max-w-md mx-auto">
          <div class="bg-white/80 backdrop-blur-lg rounded-2xl p-8 border border-gray-200/50 shadow-2xl">
            <div class="text-center mb-6">
              <img
                src="/verifiedcc-logo.png"
                alt="VerifiedCC Logo"
                class="h-16 w-auto mx-auto mb-4"
              />
              <h3 class="text-2xl font-bold text-deep-ocean">
                {isSignUp() ? "Become Our Partner" : "Become Our Partner"}
              </h3>
              <p class="text-gray-600 mt-2">
                {isSignUp()
                  ? "Partner Registration"
                  : "Access Guardian Verifiable Credentials Portal"}
              </p>
              {error() && (
                <div class="mt-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg text-sm">
                  {error()}
                </div>
              )}
            </div>

            {!isSignUp() ? (
              <form onSubmit={handleSubmit} class="space-y-6">
                <div>
                  <label
                    for="email"
                    class="block text-sm font-medium text-deep-ocean mb-2"
                  >
                    Email Address
                  </label>
                  <input
                    type="email"
                    id="email"
                    value={email()}
                    onInput={(e) => setEmail(e.currentTarget.value)}
                    required
                    class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oasis-green focus:border-transparent transition-colors bg-white/50"
                    placeholder="partner@company.com"
                  />
                </div>

                <div>
                  <label
                    for="password"
                    class="block text-sm font-medium text-deep-ocean mb-2"
                  >
                    Password
                  </label>
                  <input
                    type="password"
                    id="password"
                    value={password()}
                    onInput={(e) => setPassword(e.currentTarget.value)}
                    required
                    class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oasis-green focus:border-transparent transition-colors bg-white/50"
                    placeholder="••••••••"
                  />
                  <p class="text-xs text-gray-500 mt-1">
                    Demo credentials:{" "}
                    <code class="bg-gray-100 px-1 rounded">demo@gmail.com</code>{" "}
                    / <code class="bg-gray-100 px-1 rounded">verifiedcc</code>
                  </p>
                </div>

                {email() && password() ? (
                  <InteractiveElement
                    as="button"
                    size="small"
                    backgroundStyle="full"
                    type="submit"
                    disabled={loading()}
                    class="w-full text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
                  >
                    {loading() ? (
                      <div class="flex items-center justify-center">
                        <BouncyDotsLoader size="sm" className="mr-2" />
                        Signing In...
                      </div>
                    ) : (
                      <>
                        <LogIn class="w-5 h-5 inline mr-2" />
                        Access Dashboard
                      </>
                    )}
                  </InteractiveElement>
                ) : (
                  <button
                    type="submit"
                    disabled={loading()}
                    class="w-full text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none bg-gray-400"
                  >
                    {loading() ? (
                      <div class="flex items-center justify-center">
                        <BouncyDotsLoader size="sm" className="mr-2" />
                        Signing In...
                      </div>
                    ) : (
                      <>
                        <LogIn class="w-5 h-5 inline mr-2" />
                        Access Dashboard
                      </>
                    )}
                  </button>
                )}
              </form>
            ) : (
              <form onSubmit={handleSubmit} class="space-y-6">
                <div>
                  <label
                    for="signup_email"
                    class="block text-sm font-medium text-deep-ocean mb-2"
                  >
                    Email Address
                  </label>
                  <input
                    type="email"
                    id="signup_email"
                    value={email()}
                    onInput={(e) => setEmail(e.currentTarget.value)}
                    required
                    class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oasis-green focus:border-transparent transition-colors bg-white/50"
                    placeholder="partner@company.com"
                  />
                </div>

                <div>
                  <label
                    for="signup_password"
                    class="block text-sm font-medium text-deep-ocean mb-2"
                  >
                    Password
                  </label>
                  <input
                    type="password"
                    id="signup_password"
                    value={password()}
                    onInput={(e) => setPassword(e.currentTarget.value)}
                    required
                    class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oasis-green focus:border-transparent transition-colors bg-white/50"
                    placeholder="••••••••"
                  />
                </div>

                <div class="flex gap-3">
                  <button
                    type="submit"
                    disabled={loading()}
                    class="flex-1 bg-oasis-green hover:bg-green-700 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
                  >
                    {loading() ? (
                      <div class="flex items-center justify-center">
                        <BouncyDotsLoader size="sm" className="mr-2" />
                        Creating Account...
                      </div>
                    ) : (
                      <>
                        <UserPlus size={20} class="inline mr-2" />
                        Create Account
                      </>
                    )}
                  </button>
                  <button
                    type="button"
                    onClick={() => setIsSignUp(false)}
                    class="flex-1 bg-gray-500 hover:bg-gray-600 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300"
                  >
                    Cancel
                  </button>
                </div>
              </form>
            )}

            {!isSignUp() && (
              <div class="mt-4">
                <div class="relative">
                  <div class="absolute inset-0 flex items-center">
                    <div class="w-full border-t border-gray-300"></div>
                  </div>
                  <div class="relative flex justify-center text-sm">
                    <span class="px-2 bg-white/80 text-gray-500">Or</span>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleDemoLogin}
                  disabled={loading()}
                  class="w-full mt-4 bg-gray-500 hover:bg-gray-600 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none"
                >
                  {loading() ? (
                    <div class="flex items-center justify-center">
                      <BouncyDotsLoader size="sm" className="mr-2" />
                      Loading Demo...
                    </div>
                  ) : (
                    <>
                      <PlayCircle size={20} class="inline mr-2" />
                      Try Demo Account
                    </>
                  )}
                </button>
              </div>
            )}

            <div class="mt-6 text-center">
              <p class="text-sm text-gray-600">
                {isSignUp() ? "Already have an account?" : "New partner?"}{" "}
                <button
                  type="button"
                  onClick={() => setIsSignUp(!isSignUp())}
                  class="text-oasis-green hover:text-green-700 font-medium underline"
                >
                  {isSignUp() ? "Sign in here" : "Sign up for partnership"}
                </button>
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default SigninPage;
